# Generated by Django 6.0.6 on 2026-06-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                default="0000000000000",
                help_text="13 Character ISBN number",
                max_length=13,
                verbose_name="ISBN",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(
                default="No description",
                help_text="Enter a brief description of the book",
                max_length=1000,
            ),
            preserve_default=False,
        ),
    ]
