# Generated by Django 6.0.6 on 2026-06-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_bookinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="due_back",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="m",
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
