# Generated by Django 6.0.6 on 2026-06-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_bookinstance_borrower_alter_book_genre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookinstance",
            options={"permissions": (("can_mark_returned", "Set book as returned"),)},
        ),
    ]
