# Generated by Django 6.0.6 on 2026-06-16 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="db_comment",
            new_name="comment",
        ),
    ]
