# Generated by Django 6.0.6 on 2026-06-17 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_reservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="reserved_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="reservation",
            name="reserved_date",
            field=models.DateField(default=datetime.date(2026, 6, 17)),
            preserve_default=False,
        ),
    ]
